kind: BuildConfig
apiVersion: v1
metadata:
   name: pbc 
   namespace: p3
spec:
   source:
     git:
       ref: master
       uri: https://github.com/karthik1113bitcoin/p3.git
   strategy:
     type: JenkinsPipeline
        jenkinsPipelineStrategy:
         jenkinsfilePath: Jenkinsfile
output: {}
